TEEBLOG/Controllers/AdminController.cs
using Core.DbContext;
using Core.Models;
using Core.ViewModels;
using Logic.IHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Reflection.Metadata;

namespace TEEBLOG.Controllers
{
    [Authorize(Roles ="Admin, SuperAdmin")]
	public class AdminController : Controller
    { 
        private readonly AppDBContext _context;
        private readonly IUserHelper _userHelper;
        public AdminController(AppDBContext context, IUserHelper userHelper) 
        {
            _context = context;
            _userHelper = userHelper;  
        }

		public IActionResult Dashboard()
		{
            var cate = _context.Categories.ToList();
            var blog = _context.Blogs.Include(a => a.Categories).ToList();
            
            var result = new List<SupportViewModel>();
            var mainSupport = _context.Supports.Where(x => x.Message != null).Include(c => c.Customers).ToList();
            if (mainSupport.Any())
            {
                result = mainSupport.Select(x => new SupportViewModel()
                {
                    Message = x.Message,
                    Subject = x.Subject,
                    CustomerId = x.CustomerId,
                    Date = x.Date,
                    Customers = x.Customers,
                    Email = x.Customers.Email,
                    Name = x.Customers.Name,
                }).ToList();
            }   
           
            var dashboard = new DashboardViewModel {
                blogs = blog,
                categories = cate,
                
                supports = result,
            };
            
            return View(dashboard);
            //return View();
		}

        [HttpGet]
        public IActionResult Category()
        
        {
            IEnumerable<Category>categories = _context.Categories.ToList(); 
            return View(categories);
        }

        //for Category
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View(); 
        }

        [HttpPost]
        public IActionResult AddCategory(Category category)
        {
            var isExisting = _userHelper.GetExistingCategory(category?.Name);
            if (isExisting != null)
            {
                isExisting.Error = "Name already Exist";
                return View(isExisting);
            }
            if (category != null)
            {
                category.DateCreated = DateTime.Now;
                category.Active = true;
                _context.Categories.Add(category);
                _context.SaveChanges();
                TempData["Message"] = "Review Approved";

                //category.Success = "Name successfully Added";
                //return RedirectToAction("Category");

            }
            return RedirectToAction("Category");
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _context.Categories.Where(x => x.Id == id).FirstOrDefault();
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            var isExisting = _userHelper.GetExistingCategory(category?.Name);
            if (isExisting != null)
            {
                isExisting.Error = "Name already Exist";
                return View(isExisting);
            }
            if (category != null)
            {
                category.DateCreated = DateTime.Now;
                category.Active = true;
                _context.Categories.Update(category);
                _context.SaveChanges();
                category.Success = "Name successfully Edited";
                return RedirectToAction("Category");
            }
            return View(category);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _context.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
			var category = _context.Categories.Where(x => x.Id == id).FirstOrDefault();
            if (category != null)
            {
                _context.Categories.Remove(category);
                _context.SaveChanges();
                return RedirectToAction("Category");

            }
            return View(category);
        }
    }

}

TEEBLOG/Controllers/BlogController.cs
using Core.DbContext;
using Core.Models;
using Core.ViewModels;
using Logic.Helper;
using Logic.IHelper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Reflection.Metadata;
using System.Xml.Linq;

namespace TEEBLOG.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IDropdownHelper _dropdownHelper; 
        private readonly IUserHelper _userHelper;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogController(AppDBContext context, IDropdownHelper dropdownHelper, IUserHelper userHelper, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _dropdownHelper = dropdownHelper;
            _userHelper = userHelper;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Blog(int? name)
        {
            IEnumerable<Blog> blogs = _context.Blogs.Include(c => c.Categories).ToList();
            return View(blogs);
            
        }
        public IActionResult AdminBlogPage()
        {

            IEnumerable<Blog>blogs = _context.Blogs.Include(c => c.Categories).ToList();
            return View(blogs);
        }

        [HttpGet]
        public IActionResult AddBlogPost()
        {
            ViewBag.Categories = _dropdownHelper.DropdownOfCategories(); 
            return View();
        }

        [HttpPost]
        public JsonResult Addblog(string allPosts) 
        {
            ViewBag.Categories = _dropdownHelper.DropdownOfCategories();

            if (allPosts != null)
            {
                var data = JsonConvert.DeserializeObject<Blog>(allPosts);
                
                if (data != null)
                {
                    var result = _userHelper.CreateBlog(data);
                    if (result)
                    {
                        return Json(new { isError = false, message = "Post successfully added.", url = "/Blog/AdminBlogPage" });
                    }

                    return Json(new { isError = true, message = "Post Not Successful", url = "/Blog/AddBlogPost" });
                }
                return Json(new { isError = true, message = "Post Not Successful", url = "/Blog/AddBlogPost" });
            }
            return Json(new { isError = true, message = "Post Not Successful", url = "/Admin/Dashboard"});
        }
        [HttpGet]
        
        public IActionResult Edit(int? id)
        {
            ViewBag.Categories = _dropdownHelper.DropdownOfCategories();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var blog = _context.Blogs.Find(id);
            if (blog != null)
            {
                return View(blog);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(Blog blog)
        {
            ViewBag.Categories = _dropdownHelper.DropdownOfCategories();
            if (blog != null)
            {
                var webRoot = _webHostEnvironment.WebRootPath;
                var images = _userHelper.UploadedFile(blog.Image,webRoot);
                blog.DateCreated = DateTime.Now;
                blog.Name = blog.Name;
                blog.ShortDescription = blog.ShortDescription;
                blog.Description = blog.Description;
                blog.Picture = images;
                blog.CategoryId = blog.CategoryId;
               
                _context.Blogs.Update(blog);
                _context.SaveChanges();
                return RedirectToAction("AdminBlogPage");

            }
           
            return View(blog);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            ViewBag.Categories = _dropdownHelper.DropdownOfCategories();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var blog = _context.Blogs.Find(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            ViewBag.Categories = _dropdownHelper.DropdownOfCategories();
            var blog = _context.Blogs.Find(id);
            if (blog != null)
            {
                _context.Blogs.Remove(blog);
                _context.SaveChanges();
                return RedirectToAction("AdminBlogPage");

            }
            return View(blog);
        }

        public IActionResult ShowBlogPage(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var blog = _context.Blogs.Find(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
            
        }

        [HttpGet]
        public JsonResult GetDescription(int? id)
        {
            try
            {
                if (id > 0)
                {
                    var description = _context.Blogs.Where(x => x.Id == id && !x.Deleted && x.Active).FirstOrDefault();
                    if (description != null)
                    {
                        return Json(new { isError = false, data = description });
                    }
                }
                return Json(new { isError = true, message = "No description found!" });
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult Show(int? name)
        {
            if (name == null || name == 0)
            {
                return RedirectToAction("Category", "Category");
            }
            var blog = _context.Blogs.Find(name);
            if (blog != null)
            {
                var model = new BlogViewModel()
                {
                    Id = blog.Id,
                    Name = blog.Name,
                    CategoryId = blog.CategoryId,
                    Picture = blog.Picture,
                    ShortDescription = blog.ShortDescription,
                    Description = blog.Description,
                    DateCreated = blog.DateCreated,
                    Reviews = _userHelper.GetListOfReviews(blog.Id)
                };
                return View(model);
            }
            return RedirectToAction("Category", "Category");
        }

    }

}

TEEBLOG/Controllers/FAQsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TEEBLOG.Controllers
{
    public class FAQsController : Controller
    {
        public IActionResult FAQs()
        {
            return View();
        }
    }
}

TEEBLOG/Views/Shared/_AdminLayout.cshtml
@inject Logic.IHelper.IUserHelper _userHelper
@{
    var user = _userHelper.FindUserByEmail(User.Identity.Name);
    var userRole = _userHelper.GetUserRole(user.Id);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TEEBLOG</title>




    <script src="~/js/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/smoothscroll.js"></script>
    <script src="~/lib/jquery/dist/wow.min.js"></script>
    <script src="~/lib/jquery/dist/owl.carousel.min.js"></script>
    <script src="~/js/summernote/dist/summernote.js"></script>
    <script src="~/js/summernote/dist/summernote-bs4.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"> </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/sweetalert.min.js"></script>
    <script src="~/js/sweetalert2.all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Teeblog.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <!-- include summernote css -->
    <link href="~/js/summernote/dist/summernote.css" rel="stylesheet" />
    <link href="~/js/summernote/dist/summernote-bs4.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TEEBLOG.styles.css" asp-append-version="true" />
    <link href="~/css/sweetalert.min.css" rel="stylesheet" />
    <link href="~/css/sweetalert2.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/img/" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />


    <script>
		function errorAlert(message) {
			Swal.fire({
                title: 'Oops',
				icon: 'error',
				text: message,
				timer: 60000,
				confirmButtonColor: "red",
			})
		}

		function infoAlert(message) {
			Swal.fire({
                title: 'Incorrect Details',
				icon: 'info',
				text: message,
				confirmButtonColor: "blue",
			})
		}

		function newSuccessAlert(message, url) {
			Swal.fire({
                title: 'Successful',
				icon: 'success',
				text: message,
				confirmButtonColor: "green",
			}).then((isConfirm) => {
				if (isConfirm) {
                    location.href = url;
				}
			})
		}
	</script>


   

       
</head>

<body class="bg-light">
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-white fixed-top mb-2 p-3">
            <div class="container-fluid" style="color: #012970;">
                <p class="navbar-brand font-2 font-weight-bold" style="color: #012970;">TeeBlog</p>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> 
                <div class="navbar-collapse collapse justify-content-end" style="color: #012970;">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="color: #012970;" asp-controller="" asp-action=""> </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <aside class="sidebar bg-white">
        <ul class="sidebar-nav mt-3">
            <li class="nav-item">
                <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="Admin" asp-action="Dashboard"> <i class="fa fa-tachometer icon"></i>&nbsp; Dashboard </a>
                <hr class="dropdown-divider" />
            </li>
            <li class="nav-item">
                <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="Admin" asp-action="Category"> <i class="fa fa-book icon"></i>&nbsp; Category </a>
                <hr class="dropdown-divider" />
            </li>
                @if (userRole?.ToLower() == "super")
                {
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" 
                        style="color: #012970;" asp-controller="SuperAdmin" asp-action="SuperAdminBlogPage"> <i class="fa fa-pencil-square-o icon"></i>&nbsp; BlogPost </a>
                        <hr class="dropdown-divider" />
                </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" 
                        style="color: #012970;" asp-controller="Blog" asp-action="AdminBlogPage"> <i class="fa fa-pencil-square-o icon"></i>&nbsp; BlogPost </a>
                        <hr class="dropdown-divider" />
                    </li>
                }

                 <li class="nav-item">
                    <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="SuperAdmin" asp-action="ApprovedPosts"><i class="fa fa-check" icon"></i>&nbsp; ApprovedPosts </a>
                        <hr class="dropdown-divider" />
                 </li>
                 <li class="nav-item">
                     <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="Contact" asp-action="AdminContactPage"> <i class="fa fa-envelope icon"></i>&nbsp; Contact </a>
                     <hr class="dropdown-divider" />
                 </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="Reviews" asp-action="AdminReviews"><i class="fa fa-comments icon"></i>&nbsp; Comments </a>
                    <hr class="dropdown-divider" />
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="FAQs" asp-action="FAQs"> <i class="fa fa-question-circle icon"></i>&nbsp; FAQs </a>
                    <hr class="dropdown-divider" />
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" style="color: #012970;" asp-controller="Account" asp-action="Logout"> <i class="fa fa-sign-out icon"></i>&nbsp; Logout </a>
                </li>
                </ul>
                </aside>


                <div class="container">
                    <main role="main" class="pb-2 bg-light">
                        @RenderBody()
                    </main>
                </div>
                <footer class="footer text-dark" id="master">
                    <hr style="width: 100%; text-align: center;" />
                    <div class="container text-center" style="font-family: 'Times New Roman';">
                        <p>  &copy; 2022 - TeeBlog - All Rights Reserved.T<sup>M</sup></p>
                    </div>
                </footer>
                @await RenderSectionAsync("Scripts", required: false)
   </body>
</html>

TEEBLOG/Views/Shared/_UserVerificationLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TEEBLOG</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert2.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TEEBLOG.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/img/" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/js/summernote/dist/summernote.css" rel="stylesheet" />
    <link href="~/js/summernote/dist/summernote-bs4.css" rel="stylesheet" />
    <link href="~/js/summernote/dist/summernote-lite.css" rel="stylesheet" />
    <script>
        function newSuccessAlert(message, url) {
            debugger;
            Swal.fire({
                title: "SUCCEEDED",
                icon: "success",
                text: message,
                confirmButtonColor: "skyblue",
            }).then((isConfirm) => {
                if (isConfirm) {
                    location.href = url;
                }
            })

        }

                //function newSweetAlert(msg, url) {
                //    debugger;
                //    Swal.fire({
                //        Icon: 'success',
                //        text: msg,
                //        showDenyButton: false,
                //        showCancelButton: true,
                //        confirmButtonText: 'Ok',
                //    }).then((result) => {
                //        debugger;
                //        if (result.isConfirmed) {
                //            debugger;
                //            location.reload(url);
                //        }
                //    })
                //}
    </script>

</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark text-white p-3">
        <div class="container text-center" style="font-family: 'Times New Roman';">
            <p>  &copy; 2022 - TeeBlog - All Rights Reserved.T<sup>M</sup></p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrapjs.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="~/lib/jquery/dist/custom.js"></script>*@
    <script src="~/lib/jquery/dist/smoothscroll.js"></script>
    <script src="~/lib/jquery/dist/wow.min.js"></script>
    <script src="~/lib/jquery/dist/owl.carousel.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Teeblog.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.all.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/summernote/dist/summernote.js"></script>
    <script src="~/js/summernote/dist/summernote-bs4.js"></script>
    <script src="~/js/summernote/dist/summernote-lite.js"></script>
    <script src="~/js/sweetalert.min.js" asp-append-version="true"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>*@
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>